export const timeZoneDatas = [
  { label: "Dateline Standard Time", value: "Etc/GMT+12" },
  { label: "UTC-11", value: "Etc/GMT+11" },
  { label: "Aleutian Standard Time", value: "America/Adak" },
  { label: "Hawaiian Standard Time", value: "Pacific/Honolulu" },
  { label: "Marquesas Standard Time", value: "Pacific/Marquesas" },
  { label: "Alaskan Standard Time", value: "America/Anchorage" },
  { label: "UTC-09", value: "Etc/GMT+9" },
  { label: "Pacific Standard Time (Mexico)", value: "America/Tijuana" },
  { label: "UTC-08", value: "Etc/GMT+8" },
  { label: "Pacific Standard Time", value: "America/Los_Angeles" },
  { label: "US Mountain Standard Time", value: "America/Phoenix" },
  { label: "Mountain Standard Time (Mexico)", value: "America/Chihuahua" },
  { label: "Mountain Standard Time", value: "America/Denver" },
  { label: "Central America Standard Time", value: "America/Guatemala" },
  { label: "Central Standard Time", value: "America/Chicago" },
  { label: "Easter Island Standard Time", value: "Pacific/Easter" },
  { label: "Central Standard Time (Mexico)", value: "America/Mexico_City" },
  { label: "Canada Central Standard Time", value: "America/Regina" },
  { label: "SA Pacific Standard Time", value: "America/Bogota" },
  { label: "Eastern Standard Time (Mexico)", value: "America/Cancun" },
  { label: "Eastern Standard Time", value: "America/New_York" },
  { label: "Haiti Standard Time", value: "America/Port-au-Prince" },
  { label: "Cuba Standard Time", value: "America/Havana" },
  { label: "US Eastern Standard Time", value: "America/Indianapolis" },
  { label: "Turks And Caicos Standard Time", value: "America/Grand_Turk" },
  { label: "Paraguay Standard Time", value: "America/Asuncion" },
  { label: "Atlantic Standard Time", value: "America/Halifax" },
  { label: "Venezuela Standard Time", value: "America/Caracas" },
  { label: "Central Brazilian Standard Time", value: "America/Cuiaba" },
  { label: "SA Western Standard Time", value: "America/La_Paz" },
  { label: "Pacific SA Standard Time", value: "America/Santiago" },
  { label: "Newfoundland Standard Time", value: "America/St_Johns" },
  { label: "Tocantins Standard Time", value: "America/Araguaina" },
  { label: "E. South America Standard Time", value: "America/Sao_Paulo" },
  { label: "SA Eastern Standard Time", value: "America/Cayenne" },
  { label: "Argentina Standard Time", value: "America/Buenos_Aires" },
  { label: "Greenland Standard Time", value: "America/Godthab" },
  { label: "Montevideo Standard Time", value: "America/Montevideo" },
  { label: "Magallanes Standard Time", value: "America/Punta_Arenas" },
  { label: "Saint Pierre Standard Time", value: "America/Miquelon" },
  { label: "Bahia Standard Time", value: "America/Bahia" },
  { label: "UTC-02", value: "Etc/GMT+2" },
  { label: "Azores Standard Time", value: "Atlantic/Azores" },
  { label: "Cape Verde Standard Time", value: "Atlantic/Cape_Verde" },
  { label: "UTC", value: "Etc/GMT" },
  { label: "GMT Standard Time", value: "Europe/London" },
  { label: "Greenwich Standard Time", value: "Atlantic/Reykjavik" },
  { label: "Sao Tome Standard Time", value: "Africa/Sao_Tome" },
  { label: "Morocco Standard Time", value: "Africa/Casablanca" },
  { label: "W. Europe Standard Time", value: "Europe/Berlin" },
  { label: "Central Europe Standard Time", value: "Europe/Budapest" },
  { label: "Romance Standard Time", value: "Europe/Paris" },
  { label: "Central European Standard Time", value: "Europe/Warsaw" },
  { label: "W. Central Africa Standard Time", value: "Africa/Lagos" },
  { label: "Jordan Standard Time", value: "Asia/Amman" },
  { label: "GTB Standard Time", value: "Europe/Bucharest" },
  { label: "Middle East Standard Time", value: "Asia/Beirut" },
  { label: "Egypt Standard Time", value: "Africa/Cairo" },
  { label: "E. Europe Standard Time", value: "Europe/Chisinau" },
  { label: "Syria Standard Time", value: "Asia/Damascus" },
  { label: "West Bank Standard Time", value: "Asia/Hebron" },
  { label: "South Africa Standard Time", value: "Africa/Johannesburg" },
  { label: "FLE Standard Time", value: "Europe/Kiev" },
  { label: "Israel Standard Time", value: "Asia/Jerusalem" },
  { label: "Kaliningrad Standard Time", value: "Europe/Kaliningrad" },
  { label: "Sudan Standard Time", value: "Africa/Khartoum" },
  { label: "Libya Standard Time", value: "Africa/Tripoli" },
  { label: "Namibia Standard Time", value: "Africa/Windhoek" },
  { label: "Arabic Standard Time", value: "Asia/Baghdad" },
  { label: "Turkey Standard Time", value: "Europe/Istanbul" },
  { label: "Arab Standard Time", value: "Asia/Riyadh" },
  { label: "Belarus Standard Time", value: "Europe/Minsk" },
  { label: "Russian Standard Time", value: "Europe/Moscow" },
  { label: "E. Africa Standard Time", value: "Africa/Nairobi" },
  { label: "Iran Standard Time", value: "Asia/Tehran" },
  { label: "Arabian Standard Time", value: "Asia/Dubai" },
  { label: "Astrakhan Standard Time", value: "Europe/Astrakhan" },
  { label: "Azerbaijan Standard Time", value: "Asia/Baku" },
  { label: "Russia Time Zone 3", value: "Europe/Samara" },
  { label: "Mauritius Standard Time", value: "Indian/Mauritius" },
  { label: "Saratov Standard Time", value: "Europe/Saratov" },
  { label: "Georgian Standard Time", value: "Asia/Tbilisi" },
  { label: "Volgograd Standard Time", value: "Europe/Volgograd" },
  { label: "Caucasus Standard Time", value: "Asia/Yerevan" },
  { label: "Afghanistan Standard Time", value: "Asia/Kabul" },
  { label: "West Asia Standard Time", value: "Asia/Tashkent" },
  { label: "Ekaterinburg Standard Time", value: "Asia/Yekaterinburg" },
  { label: "Pakistan Standard Time", value: "Asia/Karachi" },
  { label: "Qyzylorda Standard Time", value: "Asia/Qyzylorda" },
  { label: "India Standard Time", value: "Asia/Calcutta" },
  { label: "Sri Lanka Standard Time", value: "Asia/Colombo" },
  { label: "Nepal Standard Time", value: "Asia/Katmandu" },
  { label: "Central Asia Standard Time", value: "Asia/Almaty" },
  { label: "Bangladesh Standard Time", value: "Asia/Dhaka" },
  { label: "Omsk Standard Time", value: "Asia/Omsk" },
  { label: "Myanmar Standard Time", value: "Asia/Rangoon" },
  { label: "SE Asia Standard Time", value: "Asia/Bangkok" },
  { label: "Altai Standard Time", value: "Asia/Barnaul" },
  { label: "W. Mongolia Standard Time", value: "Asia/Hovd" },
  { label: "North Asia Standard Time", value: "Asia/Krasnoyarsk" },
  { label: "N. Central Asia Standard Time", value: "Asia/Novosibirsk" },
  { label: "Tomsk Standard Time", value: "Asia/Tomsk" },
  { label: "China Standard Time", value: "Asia/Shanghai" },
  { label: "North Asia East Standard Time", value: "Asia/Irkutsk" },
  { label: "Singapore Standard Time", value: "Asia/Singapore" },
  { label: "W. Australia Standard Time", value: "Australia/Perth" },
  { label: "Taipei Standard Time", value: "Asia/Taipei" },
  { label: "Ulaanbaatar Standard Time", value: "Asia/Ulaanbaatar" },
  { label: "Aus Central W. Standard Time", value: "Australia/Eucla" },
  { label: "Transbaikal Standard Time", value: "Asia/Chita" },
  { label: "Tokyo Standard Time", value: "Asia/Tokyo" },
  { label: "North Korea Standard Time", value: "Asia/Pyongyang" },
  { label: "Korea Standard Time", value: "Asia/Seoul" },
  { label: "Yakutsk Standard Time", value: "Asia/Yakutsk" },
  { label: "Cen. Australia Standard Time", value: "Australia/Adelaide" },
  { label: "AUS Central Standard Time", value: "Australia/Darwin" },
  { label: "E. Australia Standard Time", value: "Australia/Brisbane" },
  { label: "AUS Eastern Standard Time", value: "Australia/Sydney" },
  { label: "West Pacific Standard Time", value: "Pacific/Port_Moresby" },
  { label: "Tasmania Standard Time", value: "Australia/Hobart" },
  { label: "Vladivostok Standard Time", value: "Asia/Vladivostok" },
  { label: "Lord Howe Standard Time", value: "Australia/Lord_Howe" },
  { label: "Bougainville Standard Time", value: "Pacific/Bougainville" },
  { label: "Russia Time Zone 10", value: "Asia/Srednekolymsk" },
  { label: "Magadan Standard Time", value: "Asia/Magadan" },
  { label: "Norfolk Standard Time", value: "Pacific/Norfolk" },
  { label: "Sakhalin Standard Time", value: "Asia/Sakhalin" },
  { label: "Central Pacific Standard Time", value: "Pacific/Guadalcanal" },
  { label: "Russia Time Zone 11", value: "Asia/Kamchatka" },
  { label: "New Zealand Standard Time", value: "Pacific/Auckland" },
  { label: "UTC+12", value: "Etc/GMT-12" },
  { label: "Fiji Standard Time", value: "Pacific/Fiji" },
  { label: "Chatham Islands Standard Time", value: "Pacific/Chatham" },
  { label: "UTC+13", value: "Etc/GMT-13" },
  { label: "Tonga Standard Time", value: "Pacific/Tongatapu" },
  { label: "Samoa Standard Time", value: "Pacific/Apia" },
  { label: "Line Islands Standard Time", value: "Pacific/Kiritimati" },
];

export const movieSortDatas = [
  { label: "ASC", value: "asc" },
  { label: "DESC", value: "desc" },
  { label: "Release Date ASC", value: "release_date_asc" },
  { label: "Release Date DESC", value: "release_date_desc" },
];
